
package veebiteenused;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TwitterPortType", targetNamespace = "http://veebiteenused.ttu.ee")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TwitterPortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.Comment
     */
    @WebMethod(operationName = "GetComment")
    @WebResult(name = "GetCommentResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/GetCommentRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/GetCommentResponse")
    public Comment getComment(
        @WebParam(name = "GetCommentRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        GetCommentRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.TweetWithComments
     */
    @WebMethod(operationName = "AddCommentToTweet")
    @WebResult(name = "AddCommentToTweetResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/AddCommentToTweetRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/AddCommentToTweetResponse")
    public TweetWithComments addCommentToTweet(
        @WebParam(name = "AddCommentToTweetRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        AddCommentToTweetRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.Tweet
     */
    @WebMethod(operationName = "GetTweet")
    @WebResult(name = "GetTweetResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetResponse")
    public Tweet getTweet(
        @WebParam(name = "GetTweetRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        GetTweetRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.Tweet
     */
    @WebMethod(operationName = "AddTweet")
    @WebResult(name = "AddTweetResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/AddTweetRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/AddTweetResponse")
    public Tweet addTweet(
        @WebParam(name = "AddTweetRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        AddTweetRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.GetTweetsResponse
     */
    @WebMethod(operationName = "GetTweets")
    @WebResult(name = "GetTweetsResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetsRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetsResponse")
    public GetTweetsResponse getTweets(
        @WebParam(name = "GetTweetsRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        GetTweetsRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.GetCommentsResponse
     */
    @WebMethod(operationName = "GetComments")
    @WebResult(name = "GetCommentsResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/GetCommentsRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/GetCommentsResponse")
    public GetCommentsResponse getComments(
        @WebParam(name = "GetCommentsRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        GetCommentsRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns veebiteenused.TweetWithComments
     */
    @WebMethod(operationName = "GetTweetComments")
    @WebResult(name = "GetTweetCommentsResponse", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
    @Action(input = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetCommentsRequest", output = "http://veebiteenused.ttu.ee/TwitterPortType/GetTweetCommentsResponse")
    public TweetWithComments getTweetComments(
        @WebParam(name = "GetTweetCommentsRequest", targetNamespace = "http://veebiteenused.ttu.ee", partName = "parameter")
        GetTweetCommentsRequest parameter);

}
