
package veebiteenused;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TwitterPortTypeService", targetNamespace = "http://veebiteenused.ttu.ee", wsdlLocation = "http://wmli118190:8080/soap_api/TwitterPortTypeService?wsdl")
public class TwitterPortTypeService
    extends Service
{

    private final static URL TWITTERPORTTYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException TWITTERPORTTYPESERVICE_EXCEPTION;
    private final static QName TWITTERPORTTYPESERVICE_QNAME = new QName("http://veebiteenused.ttu.ee", "TwitterPortTypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wmli118190:8080/soap_api/TwitterPortTypeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TWITTERPORTTYPESERVICE_WSDL_LOCATION = url;
        TWITTERPORTTYPESERVICE_EXCEPTION = e;
    }

    public TwitterPortTypeService() {
        super(__getWsdlLocation(), TWITTERPORTTYPESERVICE_QNAME);
    }

    public TwitterPortTypeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TWITTERPORTTYPESERVICE_QNAME, features);
    }

    public TwitterPortTypeService(URL wsdlLocation) {
        super(wsdlLocation, TWITTERPORTTYPESERVICE_QNAME);
    }

    public TwitterPortTypeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TWITTERPORTTYPESERVICE_QNAME, features);
    }

    public TwitterPortTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TwitterPortTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TwitterPortType
     */
    @WebEndpoint(name = "TwitterPortTypePort")
    public TwitterPortType getTwitterPortTypePort() {
        return super.getPort(new QName("http://veebiteenused.ttu.ee", "TwitterPortTypePort"), TwitterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TwitterPortType
     */
    @WebEndpoint(name = "TwitterPortTypePort")
    public TwitterPortType getTwitterPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://veebiteenused.ttu.ee", "TwitterPortTypePort"), TwitterPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TWITTERPORTTYPESERVICE_EXCEPTION!= null) {
            throw TWITTERPORTTYPESERVICE_EXCEPTION;
        }
        return TWITTERPORTTYPESERVICE_WSDL_LOCATION;
    }

}
